background {
  monitor=
  blur_passes=2
  brightness=0.817200
  contrast=0.891600
  vibrancy=0.169600
  vibrancy_darkness=0.000000
}

general {
  disable_loading_bar=true
  grace=0
}

input-field {
  monitor=
  size=300, 60
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.200000
  fade_on_empty=false
  font_color=rgb(200, 200, 200)
  font_family=FiraCode Nerd Font
  halign=center
  hide_input=false
  inner_color=rgba(255, 255, 255, 0.1)
  outer_color=rgba(255, 255, 255, 0)
  outline_thickness=2
  placeholder_text=<i><span foreground='##ffffff99'>🔒 Enter Pass</span></i>
  position=0, -210
  valign=center
}

label {
  monitor=
  color=rgba(216, 222, 233, 0.70)
  font_family=FiraCode Nerd Font
  font_size=28
  halign=center
  position=0, 490
  text=cmd[update:1000] echo -e "$(date +"%A, %B %d")"
  valign=center
}

label {
  monitor=
  color=rgba(216, 222, 233, 0.70)
  font_family=FiraCode Nerd Font
  font_size=140
  halign=center
  position=0, 370
  text=cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
  valign=center
}

label {
  monitor=
  color=rgba(216, 222, 233, 0.80)
  dots_center=true
  dots_size=0.200000
  dots_spacing=0.200000
  font_family=FiraCode Nerd Font
  font_size=18
  halign=center
  outline_thickness=2
  position=0, -130
  text= $USER
  valign=center
}
