monitor = eDP-1, 1920x1080@60., 320x1080, 1.0
monitor = HDMI-A-1, 2560x1080@89.91, 0x0, 1.0

$mainMod = SUPER
$terminal = wezterm

input {
	kb_layout = gb
	follow_mouse = 1
	touchpad {
		natural_scroll = true;
	}
}

bind = $mainMod, return, exec terminal
bind = $mainMod, W, killactive,
bind = $mainMod, A, exec, firefox
