-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
local function stylix_wrapped_config()
    return {}

end
local stylix_base_config = wezterm.config_builder()
local stylix_user_config = stylix_wrapped_config()
stylix_base_config = {
    color_scheme = "stylix",
    font = wezterm.font_with_fallback {
        "FiraCode Nerd Font Mono",
        "Noto Color Emoji",
    },
    font_size = 12,
    window_background_opacity = 0.800000,
    window_frame = {
        active_titlebar_bg = "#494d64",
        active_titlebar_fg = "#cad3f5",
        active_titlebar_border_bottom = "#494d64",
        border_left_color = "#1e2030",
        border_right_color = "#1e2030",
        border_bottom_color = "#1e2030",
        border_top_color = "#1e2030",
        button_bg = "#1e2030",
        button_fg = "#cad3f5",
        button_hover_bg = "#cad3f5",
        button_hover_fg = "#494d64",
        inactive_titlebar_bg = "#1e2030",
        inactive_titlebar_fg = "#cad3f5",
        inactive_titlebar_border_bottom = "#494d64",
    },
    colors = {
      tab_bar = {
        background = "#1e2030",
        inactive_tab_edge = "#1e2030",
        active_tab = {
          bg_color = "#24273a",
          fg_color = "#cad3f5",
        },
        inactive_tab = {
          bg_color = "#494d64",
          fg_color = "#cad3f5",
        },
        inactive_tab_hover = {
          bg_color = "#cad3f5",
          fg_color = "#24273a",
        },
        new_tab = {
          bg_color = "#494d64",
          fg_color = "#cad3f5",
        },
        new_tab_hover = {
          bg_color = "#cad3f5",
          fg_color = "#24273a",
        },
      },
    },
    command_palette_bg_color = "#1e2030",
    command_palette_fg_color = "#cad3f5",
    command_palette_font_size = 10,
}
for key, value in pairs(stylix_user_config) do
    stylix_base_config[key] = value
end
return stylix_base_config
