-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
local config = wezterm.config_builder()
config = {
    color_scheme = "stylix",
    font = wezterm.font_with_fallback {
        "FiraCode Nerd Font Mono",
        "Noto Color Emoji",
    },
    font_size = 12,
    window_background_opacity = 0.800000,
    window_frame = {
        active_titlebar_bg = "#494d64",
        active_titlebar_fg = "#cad3f5",
        active_titlebar_border_bottom = "#494d64",
        border_left_color = "#1e2030",
        border_right_color = "#1e2030",
        border_bottom_color = "#1e2030",
        border_top_color = "#1e2030",
        button_bg = "#1e2030",
        button_fg = "#cad3f5",
        button_hover_bg = "#cad3f5",
        button_hover_fg = "#494d64",
        inactive_titlebar_bg = "#1e2030",
        inactive_titlebar_fg = "#cad3f5",
        inactive_titlebar_border_bottom = "#494d64",
    },
    colors = {
      tab_bar = {
        background = "#1e2030",
        inactive_tab_edge = "#1e2030",
        active_tab = {
          bg_color = "#24273a",
          fg_color = "#cad3f5",
        },
        inactive_tab = {
          bg_color = "#494d64",
          fg_color = "#cad3f5",
        },
        inactive_tab_hover = {
          bg_color = "#cad3f5",
          fg_color = "#24273a",
        },
        new_tab = {
          bg_color = "#494d64",
          fg_color = "#cad3f5",
        },
        new_tab_hover = {
          bg_color = "#cad3f5",
          fg_color = "#24273a",
        },
      },
    },
    command_palette_bg_color = "#1e2030",
    command_palette_fg_color = "#cad3f5",
    command_palette_font_size = 10,

    hide_tab_bar_if_only_one_tab = false,
    tab_bar_at_bottom = true,
    use_fancy_tab_bar = false,
    tab_and_split_indices_are_zero_based = false,
    
    leader = { key = "q", mods = "ALT", timeout_milliseconds = 2000 },
    keys = {
	    {
		mods = "LEADER",
		key = "c",
		action = wezterm.action.SpawnTab "CurrentPaneDomain",
	    },
	    {
		mods = "LEADER",
		key = "x",
		action = wezterm.action.CloseCurrentPane { confirm = true }
	    },
	    {
		mods = "LEADER",
		key = "b",
		action = wezterm.action.ActivateTabRelative(-1)
	    },
	    {
		mods = "LEADER",
		key = "n",
		action = wezterm.action.ActivateTabRelative(1)
	    },
	    {
		mods = "LEADER",
		key = "/",
		action = wezterm.action.SplitHorizontal { domain = "CurrentPaneDomain" }
	    },
	    {
		mods = "LEADER",
		key = "-",
		action = wezterm.action.SplitVertical { domain = "CurrentPaneDomain" }
	    },
	    {
		mods = "LEADER",
		key = "h",
		action = wezterm.action.ActivatePaneDirection "Left"
	    },
	    {
		mods = "LEADER",
		key = "j",
		action = wezterm.action.ActivatePaneDirection "Down"
	    },
	    {
		mods = "LEADER",
		key = "k",
		action = wezterm.action.ActivatePaneDirection "Up"
	    },
	    {
		mods = "LEADER",
		key = "l",
		action = wezterm.action.ActivatePaneDirection "Right"
	    },
	    {
		mods = "LEADER",
		key = "LeftArrow",
		action = wezterm.action.AdjustPaneSize { "Left", 5 }
	    },
	    {
		mods = "LEADER",
		key = "RightArrow",
		action = wezterm.action.AdjustPaneSize { "Right", 5 }
	    },
	    {
		mods = "LEADER",
		key = "DownArrow",
		action = wezterm.action.AdjustPaneSize { "Down", 5 }
	    },
	    {
		mods = "LEADER",
		key = "UpArrow",
		action = wezterm.action.AdjustPaneSize { "Up", 5 }
	    },
	},
}

for i = 1, 9 do
    -- leader + number to activate that tab
    table.insert(config.keys, {
        key = tostring(i),
        mods = "LEADER",
        action = wezterm.action.ActivateTab(i),
    })
end

wezterm.on("update-right-status", function(window, _)
    local SOLID_LEFT_ARROW = ""
    local ARROW_FOREGROUND = { Foreground = { Color = "#c6a0f6" } }
    local prefix = ""

    if window:leader_is_active() then
        prefix = " " .. utf8.char(0x1f30a) -- ocean wave
        SOLID_LEFT_ARROW = utf8.char(0xe0b2)
    end

    if window:active_tab():tab_id() ~= 0 then
        ARROW_FOREGROUND = { Foreground = { Color = "#1e2030" } }
    end -- arrow color based on if tab is first pane

    window:set_left_status(wezterm.format {
        { Background = { Color = "#b7bdf8" } },
        { Text = prefix },
        ARROW_FOREGROUND,
        { Text = SOLID_LEFT_ARROW }
    })
end)


return config
